### ISSUE TITLE
webassets.exceptions.BundleError

### ISSUE THREAD

**Issue by washaweb** [harobed/coworking.a-metz.info#21]
Quand je suis tes instruction pour lancer l'environnement, à l'étape suivante : 

 ::

```
$ bin/tacot -v www
```

 j'obtiens cette erreur :

::

```
$  webassets.exceptions.BundleError: '/Users/jerome/Sites/coworking.a-metz.info/www/static/components/sequencejs/scripts/jquery.sequence.js' does not exist
```

Tu peux m'aider stp ?

**Comment by harobed** [comment]
Je regarde ça quand je quitte l'hôpital.

**Comment by harobed** [comment]
J'ai le même bug. Je corrige.

**Comment by washaweb** [comment]
Merci,

sorti de l’hôpital ?

**Comment by harobed** [comment]
Voila, j'ai patché, j'ai pinné les lib bower.

Il faut refaire un

```
$ bower install
```
